trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: _BuildCloudAccountIdArtefacts
      source: 'Build Cloud Account Id Artefacts 3.0'
    - pipeline: _BuildImageReleaseArtefacts
      source: 'Build Image Release Artefacts 3.0'
  repositories:
    - repository: _LansaAWSTemplates
      name: nkhl-accolite/aws-templates-nkhl
      type: github
      ref: feature/aws-Build-Cloud-Account-Id-Artefacts-3.0
      endpoint: nkhlLANSA
    - repository: _Robe070Cookbooks
      name: nkhl-accolite/cookbooks
      type: github
      ref: debug/paas
      endpoint: nkhlLANSA

variables:
  - group: Template Parameters
  - group: Default Branch
  - group: S3 uploads
  - group: VPC ap-southeast-2
  - group: VPC us-east-1
  - group: Git Repos
  - name: CookbooksSource1
    value: c:\lansa
  - name: imageReleaseState
    value: Production
  - name: jpnLanguage
    value: JPN
  - name: stackname
    value: BakingDP-ImageRelease
  - name: TemplateS3Namespace
    value: /image-cd-pipeline

stages:
- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v15idold'
    stageDisplayname: 'v15-id-old'
    jobName: 'w19d15idold'
    jobDisplayname: 'w19d-15-id-old'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V15-OLD'], 'true'), eq(variables['Build-all'], 'true'))

- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v13sp2idnew'
    stageDisplayname: 'v13sp2-id-new'
    jobName: 'w19d15idnew'
    jobDisplayname: 'w19d-15-id-new'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V13SP2-NEW'], 'true'), eq(variables['Build-all'], 'true'))

- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v14sp2idnew'
    stageDisplayname: 'v14sp2-id-new'
    jobName: 'w19d15idnew'
    jobDisplayname: 'w19d-15-id-new'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V14SP2-NEW'], 'True'), eq(variables['Build-all'], 'True'))

- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v15idnew'
    stageDisplayname: 'v15-id-new'
    jobName: 'w19d15idnew'
    jobDisplayname: 'w19d-15-id-new'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V15-NEW'], 'True'), eq(variables['Build-all'], 'True'))

- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v13sp2scalable'
    stageDisplayname: 'v13sp2-scalable'
    jobName: 'w19d150'
    jobDisplayname: 'w19d-15-0'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V13SP2-Scalable'], 'True'), eq(variables['Build-all'], 'True'))

- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v14sp2scalable'
    stageDisplayname: 'v14sp2-scalable'
    jobName: 'w19d150'
    jobDisplayname: 'w19d-15-0'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V14SP2-Scalable'], 'True'), eq(variables['Build-all'], 'True'))

- template: templates/releaseTemplate.yml
  parameters:
    stageName: 'v15scalable'
    stageDisplayname: 'v15-scalable'
    jobName: 'w19d150'
    jobDisplayname: 'w19d-15-0'
    jobDemand: DotNetFramework
    jobcondition: or(eq(variables['Build-V15-Scalable'], 'True'), eq(variables['Build-all'], 'True'))