trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: awstemplates_repo
  displayName: 'Source for aws-templates repo'
  type: string
  default: 'lansa/aws-templates'
- name: awstemplates_branch
  displayName: 'Source for aws-templates branch'
  type: string
  default: 'support/scalable'
- name: robe070cookbooks_repo
  displayName: 'Source for cookbooks repo'
  type: string
  default: 'robe070/cookbooks'
- name: robe070cookbooks_branch
  displayName: 'Source for cookbooks branch'
  type: string
  default: 'debug/paas'


- name: buildcloudaccountidartefacts_branch
  type: string
  default: 'feature/aws-Build-Cloud-Account-Id-Artefacts-3.0'

resources:
  pipelines:
    - pipeline: _BuildCloudAccountIdArtefacts
      project: Lansa AWS Scalable License Images
      source: Build Cloud Account Id Artefacts
      branch: ${{ parameters.buildcloudaccountidartefacts_branch }}
    - pipeline: _BuildImageReleaseArtefacts
      project: Lansa AWS Scalable License Images
      source: Build Image Release Artefacts 2.0
      branch: ${{ parameters.buildcloudaccountidartefacts_branch }}
  repositories:
    - repository: _LansaAWSTemplates
      name: lansa/aws-templates
      type: github
      ref: ${{ parameters.awstemplates_branch }}
      # endpoint: ...
    - repository: _Robe070Cookbooks
      name: cookbooks
      type: github
      ref: ${{ parameters.robe070cookbooks_branch }}
      # endpoint: ...


stages:
- template: templates/releaseStages_template.yml # Template reference
  parameters:
    stageName: 'v15'
    stageDisplayname: 'v15'
    jobName: 'w19d_15_id'
    jobDisplayname: 'w19d-15-id'

- template: templates/releaseStages_template.yml # Template reference
  parameters:
    stageName: 'v14sp2'
    stageDisplayname: 'v14sp2'
    jobName: 'w19d_15_id'
    jobDisplayname: 'w19d-15-id'

- template: templates/releaseStages_template.yml # Template reference
  parameters:
    stageName: 'v13sp2'
    stageDisplayname: 'v13sp2'
    jobName: 'w19d_15_id'
    jobDisplayname: 'w19d-15-id'