resources:
  pipelines: 
    - pipeline: _BuildCloudAccountIdArtefacts
      source: Build Cloud Account Id Artefacts 3.0
    - pipeline: _BuildImageReleaseArtefacts
      source: Build Image Release Artefacts 3.0
  repositories:
    - repository: _LansaAzureQuickstartTemplates
      name: lansa/azure-quickstart-templates
      type: github
      ref: support/scalable
      endpoint: nkhlLANSA
    - repository: _CelestialSystemAzureQuickstartTemplates
      name: CelestialSystem/azure-quickstart-templates
      type: github
      ref: feature/139
      endpoint: nkhlLANSA
    - repository: _Robe070Cookbooks
      name: robe070/cookbooks
      type: github
      ref: debug/paas
      endpoint: nkhlLANSA

stages:
  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v15
      stageDisplayname: v15
      jobName: w19d15id
      jobDisplayname: w19d-15-id

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v15
      stageDisplayname: v15
      jobName: w19d15id
      jobDisplayname: w19d-15-id