resources:
  pipelines: 
    - pipeline: _BuildCloudAccountIdArtefacts
      source: Build Cloud Account Id Artefacts 3.0
    - pipeline: _BuildImageReleaseArtefacts
      source: Build Image Release Artefacts 3.0
  repositories:
    - repository: _LansaAzureQuickstartTemplates
      # name: lansa/azure-quickstart-templates
      name: nkhl-accolite/azure-quickstart-templates-nkhl
      type: github
      # ref: support/scalable
      ref: feature/classic2yml-release
      # endpoint: priyadishah
      endpoint: nkhl-accolite
    - repository: _CelestialSystemAzureQuickstartTemplates
      name: CelestialSystem/azure-quickstart-templates
      type: github
      ref: feature/139
      endpoint: priyadishah
    - repository: _Robe070Cookbooks
      name: robe070/cookbooks
      type: github
      ref: debug/paas
      endpoint: priyadishah

variables:
  - group: Template Parameters
  - group: SKU Versions
  - group: Image Names
  - group: Azure Logins
  - group: Git Repos
  - name: CookbooksSource
    value: $(System.DefaultWorkingDirectory)\cookbooks
  - name: jpnLanguage
    value: JPN
  - name: ResourceGroupName
    value: BakingDP
  - name: SubscriptionId
    value: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3

stages:
  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v15
      stageDisplayname: v15
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V15'], 'True'), eq(variables['Build-all'], 'True'))

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v14sp2
      stageDisplayname: v14sp2
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V14SP2'], 'True'), eq(variables['Build-all'], 'True'))

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v13sp2
      stageDisplayname: v13sp2
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V13SP2'], 'True'), eq(variables['Build-all'], 'True'))

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v15scalable
      stageDisplayname: v15-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V15-scalable'], 'True'), eq(variables['Build-all'], 'True'))

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v14sp2scalable
      stageDisplayname: v14sp2-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V14SP2-scalable'], 'True'), eq(variables['Build-all'], 'True'))

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v13sp2scalable
      stageDisplayname: v13sp2-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V13SP2-Scalable'], 'True'), eq(variables['Build-all'], 'True'))