# File: azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'windows-2022'

stages:
- stage: Build
  jobs: 
  - job: npminstall
    steps:
    - pwsh: Write-Host "BUILD"

- template: templates/Cloud Account Id Image Release 3.0 _STAGES.yml # Template reference
  parameters:
    stageName: 'v15'
    stageDisplayname: 'v15'
    dependsOn: Build
    jobName: 'w19d_15_id'
    jobDisplayname: 'w19d-15-id'

- template: templates/Cloud Account Id Image Release 3.0 _STAGES.yml # Template reference
  parameters:
    stageName: 'v14sp2'
    stageDisplayname: 'v14sp2'
    dependsOn: Build
    jobName: 'w19d_15_id'
    jobDisplayname: 'w19d-15-id'

- template: templates/Cloud Account Id Image Release 3.0 _STAGES.yml # Template reference
  parameters:
    stageName: 'v13sp2'
    stageDisplayname: 'v13sp2'
    dependsOn: Build
    jobName: 'w19d_15_id'
    jobDisplayname: 'w19d-15-id'