resources:
  pipelines: 
    - pipeline: _Build Cloud Account Id Artefacts
      source: Build Cloud Account Id Artefacts 3.0
    - pipeline: _Lansa Images - Cookbooks
      source: Build Image Release Artefacts 3.0
  repositories:
    - repository: _lansa_azure-quickstart-templates
      # name: lansa/azure-quickstart-templates
      name: nkhl-accolite/azure-quickstart-templates-nkhl
      type: github
      # ref: support/scalable
      ref: feature/classic2yml-release
      # endpoint: priyadishah
      endpoint: nkhl-accolite
    - repository: _lansa_azure-quickstart-templates-celestial
      name: CelestialSystem/azure-quickstart-templates
      type: github
      ref: feature/139
      endpoint: priyadishah
    - repository: _robe070_cookbooks
      type: github
      endpoint: priyadishah
      name: priyadishah/cookbooks
      ref: feature/AWSImageRelease-3.0

variables:
  - group: Template Parameters
  - group: SKU Versions
  - group: Image Names
  - group: Azure Logins
  - group: Git Repos
  - name: CookbooksSource
    value: $(Pipeline.Workspace)\cookbooks
  - name: jpnLanguage
    value: JPN
  - name: ResourceGroupName
    value: BakingDP
  - name: SubscriptionId
    value: 739c4e86-bd75-4910-8d6e-d7eb23ab94f3

stages:
  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v15
      stageDisplayname: v15
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V15'], 'True'), eq(variables['Build-all'], 'True'))
      paramsetGateVariable: 'azure_set_gate_variable_cloud_account_id.ps1'
      parammsiURL: "$(msiURLv15)"

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v14sp2
      stageDisplayname: v14sp2
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V14SP2'], 'True'), eq(variables['Build-all'], 'True'))
      paramsetGateVariable: 'azure_set_gate_variable_cloud_account_id.ps1'
      parammsiURL: "$(msiURLv142)"

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v13sp2
      stageDisplayname: v13sp2
      jobName: w19d15id
      jobDisplayname: w19d-15-ID
      jobcondition: or(eq(variables['Build-V13SP2'], 'True'), eq(variables['Build-all'], 'True'))
      paramsetGateVariable: 'azure_set_gate_variable_cloud_account_id.ps1'
      parammsiURL: "$(msiURLv132)"

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v15scalable
      stageDisplayname: v15-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V15-scalable'], 'True'), eq(variables['Build-all'], 'True'))
      paramsetGateVariable: 'azure_set_gate_variable.ps1'
      parammsiURL: "$(msiURLv15)"

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v14sp2scalable
      stageDisplayname: v14sp2-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V14SP2-scalable'], 'True'), eq(variables['Build-all'], 'True'))
      paramsetGateVariable: 'azure_set_gate_variable.ps1'
      parammsiURL: "$(msiURLv142)"

  - template: Cloud Account Id Image Release 3.0 - template.yml
    parameters:
      stageName: v13sp2scalable
      stageDisplayname: v13sp2-scalable
      jobName: w19d150
      jobDisplayname: w19d-15-0
      jobcondition: or(eq(variables['Build-V13SP2-Scalable'], 'True'), eq(variables['Build-all'], 'True'))
      paramsetGateVariable: 'azure_set_gate_variable.ps1'
      parammsiURL: "$(msiURLv132)"