parameters:
  - name: stageName
    type: string
    default: none
  - name: stageDisplayname
    type: string
    default: none
  - name: runStage
    type: boolean
    default: true
  # - name: dependsOn
  #   default: []
  - name: jobName
    type: string
    default: none
  - name: jobDisplayname
    type: string
    default: none
  - name: vmImage
    type: string
    default: windows-2022
  - name: deploySQLservertaskname
    type: string
    default: none


stages:
  - stage: ${{ parameters.stageName }}
    condition: ${{ parameters.runStage }}
    dependsOn: []
    displayName: 'Stage: ${{ parameters.stageDisplayname }}'
    jobs:
    - job: ${{ parameters.jobName }}
      displayName: 'Job: ${{ parameters.jobDisplayname }}'
      variables:
        TemplateS3Namespace: '/image-cd-pipeline'
      pool:
        vmImage: ${{ parameters.vmImage }}
      steps:
      - pwsh: Write-Host "TESTING!"
      - download: _BuildCloudAccountIdArtefacts
      - download: _BuildImageReleaseArtefacts
      - checkout: self
      - checkout: _LansaAWSTemplates
      - checkout: _Robe070Cookbooks

      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        name: gateVariable
        displayName: 'Artifact Check: Set Gate Variable'
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          arguments: '-BaseImageName ''$(System.JobDisplayName)'' -stackname ''$(System.StageDisplayName)-$(System.JobDisplayName)'''
          filePath: '$(System.DefaultWorkingDirectory)/scripts/SetGateVariableCloudAccountId.ps1'
      
      #Your build pipeline references an undefined variable named ‘Gate.IsEnabled’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘Gate.ImageID’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘Gate.stack’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      - pwsh: |
          # Print the Gate variables.
          Write-Host "Gate.IsEnabled: $(gateVariable.Gate.IsEnabled); Gate.ImageID: $(gateVariable.Gate.ImageID); Gate.stack:$(gateVariable.Gate.stack)"| Out-Default
        
        displayName: 'Artifact Check : Output Gate Variable'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      #Your build pipeline references an undefined variable named ‘Gate.stack’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Delete previous Failed Stack'
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(System.DefaultWorkingDirectory)/_lansa_aws-templates/scripts/DeletePreviousFailedStack.ps1'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      #Your build pipeline references an undefined variable named ‘Gate.stack’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘CookbooksBranch’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘DBPasswordKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘DBPasswordValue’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘WebPasswordKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘WebPasswordValue’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘KeyNameKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘KeyNameValue’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘RemoteAccessLocationKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘RemoteAccessLocationValue’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘Gate.ImageID’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘lansaVersion’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘WebserverOSLatestVersionValue’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘CookbooksBranch’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘LansaMSIKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘msiURLLatest’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘CurrentVPC’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘AvailabilityZones’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘NumberOfAZs’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘DBSubnetGroupName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘ELBSubnetIds’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      #Your build pipeline references an undefined variable named ‘03DBUsername’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
        displayName: 'Deploy AWS template'
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          stackName: '$(Gate.stack)'
          templateSource: s3
          s3BucketName: lansa
          s3ObjectKey: 'templates/$(CookbooksBranch)$(TemplateS3Namespace)/lansa-master-win.cfn.template'
          templateParametersSource: inline
          templateParameters: |
            [{
                "ParameterKey": "$(DBPasswordKey)",
                "ParameterValue": "$(DBPasswordValue)"
            }, {
                "ParameterKey": "$(WebPasswordKey)",
                "ParameterValue": "$(WebPasswordValue)"
            }, {
                "ParameterKey": "$(KeyNameKey)",    
                "ParameterValue": "$(KeyNameValue)"
            }, {
                "ParameterKey": "$(RemoteAccessLocationKey)",   
                "ParameterValue": "$(RemoteAccessLocationValue)"
            }, {
                "ParameterKey": "ImageSource",   
                "ParameterValue": "Custom"
            }, {
                "ParameterKey": "AMIId",   
                "ParameterValue": "$(Gate.ImageID)"
            }, {
                "ParameterKey": "LansaVersion",   
                "ParameterValue": "$(lansaVersion)"
            },  {
                "ParameterKey": "11WebserverOSVersion",   
                "ParameterValue": "$(WebserverOSLatestVersionValue)"
            }, {
                "ParameterKey": "10LansaGitRepoBranch",   
                "ParameterValue": "$(CookbooksBranch)"
            },  {
                "ParameterKey": "TemplateS3Namespace",   
                "ParameterValue": "$(TemplateS3Namespace)"
            }, {
                "ParameterKey": "$(LansaMSIKey)",   
                "ParameterValue": "$(msiURLLatest)"
            }, {
                "ParameterKey": "CurrentVPC",   
                "ParameterValue": "$(CurrentVPC)"
            }, {
                "ParameterKey": "AvailabilityZones",   
                "ParameterValue": "$(AvailabilityZones)"
            }, {
                "ParameterKey": "NumberOfAZs",   
                "ParameterValue": "$(NumberOfAZs)"
            }, {
                "ParameterKey": "DBSubnetGroupName",   
                "ParameterValue": "$(DBSubnetGroupName)"
            }, {
                "ParameterKey": "ELBSubnetIds",   
                "ParameterValue": "$(ELBSubnetIds)"
            }, {
                "ParameterKey": "03DBUsername",   
                "ParameterValue": "$(03DBUsername)"
            }
            ]
          onFailure: 'DO_NOTHING'
          disableRollback: true
          outputVariable: deploymentOutput
          captureStackOutputs: asJSON
          captureAsSecuredVars: false
          timeoutInMins: 120
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      #Your build pipeline references an undefined variable named ‘Gate.stack’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Print Deployment Output'
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(System.DefaultWorkingDirectory)/_lansa_aws-templates/scripts/PrintDeploymentOutput.ps1'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      #Your build pipeline references an undefined variable named ‘Gate.stack’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Test CFN Deployment: URL tests'
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(System.DefaultWorkingDirectory)/_lansa_aws-templates/scripts/TestCFNDeployment.ps1'
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))

      #Your build pipeline references an undefined variable named ‘Gate.stack’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
      - task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
        displayName: 'Delete Stack'
        inputs:
          awsCredentials: AzureDevOps
          regionName: 'ap-southeast-2'
          arguments: '-Gatestack $(Gate.stack)'
          filePath: '$(System.DefaultWorkingDirectory)/_lansa_aws-templates/scripts/DeletePreviousFailedStack.ps1'
          ignoreLASTEXITCODE: true
        condition: and(succeeded(), eq(variables['Gate.IsEnabled'], 'True'))
        timeoutInMinutes: 240